package com.example.demo.dao.generator;

import com.example.demo.entity.generator.model.UserInfoRoleTest;
import com.example.demo.entity.generator.model.UserInfoRoleTestCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoRoleTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    long countByExample(UserInfoRoleTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    int deleteByExample(UserInfoRoleTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    int insert(UserInfoRoleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    int insertSelective(UserInfoRoleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    List<UserInfoRoleTest> selectByExample(UserInfoRoleTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    UserInfoRoleTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserInfoRoleTest record, @Param("example") UserInfoRoleTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserInfoRoleTest record, @Param("example") UserInfoRoleTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserInfoRoleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfoRoleTest record);
}