package com.example.demo.dao.generator;

import com.example.demo.entity.generator.model.UserInfoRolePO;
import com.example.demo.entity.generator.model.UserInfoRolePOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */
    long countByExample(UserInfoRolePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */
    int deleteByExample(UserInfoRolePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */
    int insert(UserInfoRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */
    List<UserInfoRolePO> selectByExample(UserInfoRolePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */
    UserInfoRolePO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserInfoRolePO record, @Param("example") UserInfoRolePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserInfoRolePO record, @Param("example") UserInfoRolePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserInfoRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfoRolePO record);
}